stages:
    - Deploy

deploy_production:
    stage: Deploy
    script:
      - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/ci-flask-server.git
      - git push heroku master
      - echo "Deployed to Production Server https://ci-flask-server.herokuapp.com"
    only:
      - master